# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET Framework

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore NuGet packages
      run: nuget restore KnightOwlBot.sln

    - name: Build
      run: msbuild KnightOwlBot.sln /p:Configuration=Release

    - name: Upload EXE as artifact
      uses: actions/upload-artifact@v3
      with:
        name: KnightOwlBot-exe
        path: KnightOwlBot\bin\Release\KnightOwlBot.exe

